// SPDX-License-Identifier: BSD-3-Clause
// Copyright Contributors to the feather-tk project.

#include <ftk/GPU/RenderPrivate.h>

namespace ftk
{
    namespace gpu
    {
        // These say what the OpenGL renderer's shaders say; see
        // ftk/GL/RenderShaders.cpp, which is where the reasons are.
        //
        // A stage is compiled on its own, so what passes from one to the
        // next is matched by its user() attribute. Uniforms are a block in
        // buffer zero of the stage, and textures and samplers go by index.

        namespace
        {
            const std::string header =
                "#include <metal_stdlib>\n"
                "using namespace metal;\n"
                "\n";
        }

        std::string vertexSourceMSL()
        {
            return header +
                "struct VertexIn\n"
                "{\n"
                "    float2 pos [[attribute(0)]];\n"
                "    float2 uv [[attribute(1)]];\n"
                "};\n"
                "\n"
                "struct VertexOut\n"
                "{\n"
                "    float4 position [[position]];\n"
                "    float2 uv [[user(locn0)]];\n"
                "};\n"
                "\n"
                "struct Uniforms\n"
                "{\n"
                "    float4x4 mvp;\n"
                "};\n"
                "\n"
                "vertex VertexOut vertexMain(\n"
                "    VertexIn in [[stage_in]],\n"
                "    constant Uniforms& u [[buffer(0)]])\n"
                "{\n"
                "    VertexOut out;\n"
                "    out.position = u.mvp * float4(in.pos, 0.0, 1.0);\n"
                "    out.uv = in.uv;\n"
                "    return out;\n"
                "}\n";
        }

        std::string colorMeshVertexSourceMSL()
        {
            return header +
                "struct VertexIn\n"
                "{\n"
                "    float2 pos [[attribute(0)]];\n"
                "    float4 color [[attribute(1)]];\n"
                "};\n"
                "\n"
                "struct VertexOut\n"
                "{\n"
                "    float4 position [[position]];\n"
                "    float4 color [[user(locn0)]];\n"
                "};\n"
                "\n"
                "struct Uniforms\n"
                "{\n"
                "    float4x4 mvp;\n"
                "};\n"
                "\n"
                "vertex VertexOut vertexMain(\n"
                "    VertexIn in [[stage_in]],\n"
                "    constant Uniforms& u [[buffer(0)]])\n"
                "{\n"
                "    VertexOut out;\n"
                "    out.position = u.mvp * float4(in.pos, 0.0, 1.0);\n"
                "    out.color = in.color;\n"
                "    return out;\n"
                "}\n";
        }

        namespace
        {
            const std::string fragmentIn =
                "struct VertexOut\n"
                "{\n"
                "    float4 position [[position]];\n"
                "    float2 uv [[user(locn0)]];\n"
                "};\n"
                "\n";
        }

        std::string meshFragmentSourceMSL()
        {
            return header + fragmentIn +
                "struct Uniforms\n"
                "{\n"
                "    float4 color;\n"
                "};\n"
                "\n"
                "fragment float4 fragmentMain(\n"
                "    VertexOut in [[stage_in]],\n"
                "    constant Uniforms& u [[buffer(0)]])\n"
                "{\n"
                "    return u.color;\n"
                "}\n";
        }

        std::string colorMeshFragmentSourceMSL()
        {
            return header +
                "struct VertexOut\n"
                "{\n"
                "    float4 position [[position]];\n"
                "    float4 color [[user(locn0)]];\n"
                "};\n"
                "\n"
                "struct Uniforms\n"
                "{\n"
                "    float4 color;\n"
                "};\n"
                "\n"
                "fragment float4 fragmentMain(\n"
                "    VertexOut in [[stage_in]],\n"
                "    constant Uniforms& u [[buffer(0)]])\n"
                "{\n"
                "    return in.color * u.color;\n"
                "}\n";
        }

        std::string textureFragmentSourceMSL()
        {
            return header + fragmentIn +
                "struct Uniforms\n"
                "{\n"
                "    float4 color;\n"
                "    int opaque;\n"
                "};\n"
                "\n"
                "fragment float4 fragmentMain(\n"
                "    VertexOut in [[stage_in]],\n"
                "    constant Uniforms& u [[buffer(0)]],\n"
                "    texture2d<float> t0 [[texture(0)]],\n"
                "    sampler s0 [[sampler(0)]])\n"
                "{\n"
                "    float4 outColor = t0.sample(s0, in.uv) * u.color;\n"
                "    if (u.opaque != 0)\n"
                "    {\n"
                "        outColor.a = 1.0;\n"
                "    }\n"
                "    return outColor;\n"
                "}\n";
        }

        std::string textFragmentSourceMSL()
        {
            return header + fragmentIn +
                "struct Uniforms\n"
                "{\n"
                "    float4 color;\n"
                "};\n"
                "\n"
                "fragment float4 fragmentMain(\n"
                "    VertexOut in [[stage_in]],\n"
                "    constant Uniforms& u [[buffer(0)]],\n"
                "    texture2d<float> t0 [[texture(0)]],\n"
                "    sampler s0 [[sampler(0)]])\n"
                "{\n"
                "    float4 outColor;\n"
                "    outColor.rgb = u.color.rgb;\n"
                "    float coverage = t0.sample(s0, in.uv).r * u.color.a;\n"
                "    float gamma = 1.3;\n"
                "    outColor.a = pow(coverage, 1.0 / gamma);\n"
                "    return outColor;\n"
                "}\n";
        }

        namespace
        {
            const std::string imageType =
                "// enum ftk::ImageType\n"
                "constant int ImageType_None              = 0;\n"
                "constant int ImageType_L_U8              = 1;\n"
                "constant int ImageType_L_U16             = 2;\n"
                "constant int ImageType_L_U32             = 3;\n"
                "constant int ImageType_L_F16             = 4;\n"
                "constant int ImageType_L_F32             = 5;\n"
                "constant int ImageType_LA_U8             = 6;\n"
                "constant int ImageType_LA_U32            = 7;\n"
                "constant int ImageType_LA_U16            = 8;\n"
                "constant int ImageType_LA_F16            = 9;\n"
                "constant int ImageType_LA_F32            = 10;\n"
                "constant int ImageType_RGB_U8            = 11;\n"
                "constant int ImageType_RGB_U10           = 12;\n"
                "constant int ImageType_RGB_U16           = 13;\n"
                "constant int ImageType_RGB_U32           = 14;\n"
                "constant int ImageType_RGB_F16           = 15;\n"
                "constant int ImageType_RGB_F32           = 16;\n"
                "constant int ImageType_RGBA_U8           = 17;\n"
                "constant int ImageType_RGBA_U16          = 18;\n"
                "constant int ImageType_RGBA_U32          = 19;\n"
                "constant int ImageType_RGBA_F16          = 20;\n"
                "constant int ImageType_RGBA_F32          = 21;\n"
                "constant int ImageType_YUV_420P_U8       = 22;\n"
                "constant int ImageType_YUV_422P_U8       = 23;\n"
                "constant int ImageType_YUV_444P_U8       = 24;\n"
                "constant int ImageType_YUV_420P_U16      = 25;\n"
                "constant int ImageType_YUV_422P_U16      = 26;\n"
                "constant int ImageType_YUV_444P_U16      = 27;\n"
                "constant int ImageType_YUV_420SP_U8      = 28;\n"
                "constant int ImageType_YUV_420SP_U16     = 29;\n"
                "constant int ImageType_RGB_F16_P         = 30;\n"
                "\n"
                "// enum ftk::ChannelDisplay\n"
                "constant int ChannelDisplay_Color = 0;\n"
                "constant int ChannelDisplay_Red   = 1;\n"
                "constant int ChannelDisplay_Green = 2;\n"
                "constant int ChannelDisplay_Blue  = 3;\n"
                "constant int ChannelDisplay_Alpha = 4;\n"
                "\n"
                "// enum ftk::VideoLevels\n"
                "constant int VideoLevels_FullRange  = 0;\n"
                "constant int VideoLevels_LegalRange = 1;\n"
                "\n";

            const std::string sampleTexture =
                "float codeScale(int imageType)\n"
                "{\n"
                "    float scale = 255.0;\n"
                "    if (ImageType_YUV_420P_U16 == imageType ||\n"
                "        ImageType_YUV_422P_U16 == imageType ||\n"
                "        ImageType_YUV_444P_U16 == imageType ||\n"
                "        ImageType_YUV_420SP_U16 == imageType)\n"
                "    {\n"
                "        scale = 65535.0 / 256.0;\n"
                "    }\n"
                "    return scale;\n"
                "}\n"
                "\n"
                "float4 sampleTexture(\n"
                "    float2 uv,\n"
                "    int imageType,\n"
                "    int channelCount,\n"
                "    int videoLevels,\n"
                "    float4 yuvCoefficients,\n"
                "    texture2d<float> t0,\n"
                "    texture2d<float> t1,\n"
                "    texture2d<float> t2,\n"
                "    sampler s0,\n"
                "    sampler s1,\n"
                "    sampler s2)\n"
                "{\n"
                "    float4 c = float4(0.0);\n"
                "    if (ImageType_YUV_420P_U8 == imageType ||\n"
                "        ImageType_YUV_422P_U8 == imageType ||\n"
                "        ImageType_YUV_444P_U8 == imageType ||\n"
                "        ImageType_YUV_420P_U16 == imageType ||\n"
                "        ImageType_YUV_422P_U16 == imageType ||\n"
                "        ImageType_YUV_444P_U16 == imageType ||\n"
                "        ImageType_YUV_420SP_U8 == imageType ||\n"
                "        ImageType_YUV_420SP_U16 == imageType)\n"
                "    {\n"
                "        // The interleaved chroma of the NV12 types is one plane\n"
                "        // of two channels, and the others have a plane of each.\n"
                "        bool sp =\n"
                "            ImageType_YUV_420SP_U8 == imageType ||\n"
                "            ImageType_YUV_420SP_U16 == imageType;\n"
                "        float y = t0.sample(s0, uv).r;\n"
                "        float cb = t1.sample(s1, uv).r;\n"
                "        float cr = sp ? t1.sample(s1, uv).g : t2.sample(s2, uv).r;\n"
                "        float s = codeScale(imageType);\n"
                "        if (VideoLevels_FullRange == videoLevels)\n"
                "        {\n"
                "            cb -= 128.0 / s;\n"
                "            cr -= 128.0 / s;\n"
                "        }\n"
                "        else\n"
                "        {\n"
                "            y  = (y * s - 16.0) / (235.0 - 16.0);\n"
                "            cb = (cb * s - 16.0) / (240.0 - 16.0) - 0.5;\n"
                "            cr = (cr * s - 16.0) / (240.0 - 16.0) - 0.5;\n"
                "        }\n"
                "        c.r = y + (yuvCoefficients.x * cr);\n"
                "        c.g = y - (yuvCoefficients.y * cr) - (yuvCoefficients.z * cb);\n"
                "        c.b = y + (yuvCoefficients.w * cb);\n"
                "        c.rgb = clamp(c.rgb, 0.0, 1.0);\n"
                "        c.a = 1.0;\n"
                "    }\n"
                "    else if (ImageType_RGB_F16_P == imageType)\n"
                "    {\n"
                "        c.r = t0.sample(s0, uv).r;\n"
                "        c.g = t1.sample(s1, uv).r;\n"
                "        c.b = t2.sample(s2, uv).r;\n"
                "        c.a = 1.0;\n"
                "        if (VideoLevels_LegalRange == videoLevels)\n"
                "        {\n"
                "            c.rgb = (c.rgb - (16.0 / 255.0)) * (255.0 / (235.0 - 16.0));\n"
                "        }\n"
                "    }\n"
                "    else\n"
                "    {\n"
                "        c = t0.sample(s0, uv);\n"
                "        if (VideoLevels_LegalRange == videoLevels)\n"
                "        {\n"
                "            c.rgb = (c.rgb - (16.0 / 255.0)) * (255.0 / (235.0 - 16.0));\n"
                "            if (ImageType_L_U8 == imageType ||\n"
                "                ImageType_L_U16 == imageType ||\n"
                "                ImageType_L_U32 == imageType ||\n"
                "                ImageType_LA_U8 == imageType ||\n"
                "                ImageType_LA_U16 == imageType ||\n"
                "                ImageType_LA_U32 == imageType ||\n"
                "                ImageType_RGB_U8 == imageType ||\n"
                "                ImageType_RGB_U10 == imageType ||\n"
                "                ImageType_RGB_U16 == imageType ||\n"
                "                ImageType_RGB_U32 == imageType ||\n"
                "                ImageType_RGBA_U8 == imageType ||\n"
                "                ImageType_RGBA_U16 == imageType ||\n"
                "                ImageType_RGBA_U32 == imageType)\n"
                "            {\n"
                "                c.rgb = clamp(c.rgb, 0.0, 1.0);\n"
                "            }\n"
                "        }\n"
                "        if (1 == channelCount)\n"
                "        {\n"
                "            c.g = c.b = c.r;\n"
                "            c.a = 1.0;\n"
                "        }\n"
                "        else if (2 == channelCount)\n"
                "        {\n"
                "            c.a = c.g;\n"
                "            c.g = c.b = c.r;\n"
                "        }\n"
                "        else if (3 == channelCount)\n"
                "        {\n"
                "            c.a = 1.0;\n"
                "        }\n"
                "    }\n"
                "    return c;\n"
                "}\n"
                "\n";
        }

        std::string imageFragmentSourceMSL()
        {
            return header + fragmentIn + imageType + sampleTexture +
                "struct Uniforms\n"
                "{\n"
                "    float4 color;\n"
                "    float4 yuvCoefficients;\n"
                "    int opaque;\n"
                "    int imageType;\n"
                "    int channelCount;\n"
                "    int channelDisplay;\n"
                "    int videoLevels;\n"
                "    int mirrorX;\n"
                "    int mirrorY;\n"
                "};\n"
                "\n"
                "fragment float4 fragmentMain(\n"
                "    VertexOut in [[stage_in]],\n"
                "    constant Uniforms& u [[buffer(0)]],\n"
                "    texture2d<float> t0 [[texture(0)]],\n"
                "    texture2d<float> t1 [[texture(1)]],\n"
                "    texture2d<float> t2 [[texture(2)]],\n"
                "    sampler s0 [[sampler(0)]],\n"
                "    sampler s1 [[sampler(1)]],\n"
                "    sampler s2 [[sampler(2)]])\n"
                "{\n"
                "    float2 t = in.uv;\n"
                "    if (1 == u.mirrorX)\n"
                "    {\n"
                "        t.x = 1.0 - t.x;\n"
                "    }\n"
                "    if (0 == u.mirrorY)\n"
                "    {\n"
                "        t.y = 1.0 - t.y;\n"
                "    }\n"
                "    float4 outColor = sampleTexture(\n"
                "        t,\n"
                "        u.imageType,\n"
                "        u.channelCount,\n"
                "        u.videoLevels,\n"
                "        u.yuvCoefficients,\n"
                "        t0, t1, t2, s0, s1, s2) *\n"
                "        u.color;\n"
                "    if (u.opaque != 0)\n"
                "    {\n"
                "        outColor.a = 1.0;\n"
                "    }\n"
                "    if (ChannelDisplay_Red == u.channelDisplay)\n"
                "    {\n"
                "        outColor.g = outColor.b = outColor.r;\n"
                "    }\n"
                "    else if (ChannelDisplay_Green == u.channelDisplay)\n"
                "    {\n"
                "        outColor.r = outColor.b = outColor.g;\n"
                "    }\n"
                "    else if (ChannelDisplay_Blue == u.channelDisplay)\n"
                "    {\n"
                "        outColor.r = outColor.g = outColor.b;\n"
                "    }\n"
                "    else if (ChannelDisplay_Alpha == u.channelDisplay)\n"
                "    {\n"
                "        outColor.r = outColor.g = outColor.b = outColor.a;\n"
                "    }\n"
                "    return outColor;\n"
                "}\n";
        }
    }
}
