include(ExternalProject)

set(SDL2_GIT_REPOSITORY "https://github.com/libsdl-org/SDL.git")
set(SDL2_GIT_TAG "release-2.32.10")

set(SDL2_ARGS
    ${ftk_DEPS_ARGS}
    -DSDL_ARTS=OFF
    -DSDL_DIRECTX=OFF
    -DSDL_HAPTIC=OFF
    -DSDL_HIDAPI=OFF
    -DSDL_IBUS=OFF
    -DSDL_JACK=OFF
    -DSDL_JOYSTICK=OFF
    -DSDL_KMSDRM=ON
    -DSDL_METAL=OFF
    -DSDL_NAS=OFF
    -DSDL_OPENGL=ON
    -DSDL_OPENGLES=ON
    -DSDL_RENDER_D3D=OFF
    -DSDL_RENDER_METAL=OFF
    -DSDL_RPI=OFF
    -DSDL_STATIC_PIC=ON
    -DSDL_VIVANTE=OFF
    -DSDL_VULKAN=OFF
    -DSDL_WAYLAND=ON
    -DSDL_X11=ON)

ExternalProject_Add(
    SDL2
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/SDL2
    GIT_REPOSITORY ${SDL2_GIT_REPOSITORY}
    GIT_TAG ${SDL2_GIT_TAG}
    LIST_SEPARATOR |
    CMAKE_ARGS ${SDL2_ARGS})
