// SPDX-License-Identifier: BSD-3-Clause
// Copyright Contributors to the feather-tk project.

#pragma once


#include <nanobind/nanobind.h>
#include <nanobind/stl/shared_ptr.h>
#include <nanobind/stl/string.h>

namespace ftk
{
    namespace python
    {
        void action(nanobind::module_&);
        void actionGroup(nanobind::module_&);
        void app(nanobind::module_&);
        void bellows(nanobind::module_&);
        void buttonGroup(nanobind::module_&);
        void checkBox(nanobind::module_&);
        void clipboardSystem(nanobind::module_&);
        void colorPopup(nanobind::module_&);
        void colorSlider(nanobind::module_&);
        void colorDot(nanobind::module_&);
        void colorSwatch(nanobind::module_&);
        void colorWidget(nanobind::module_&);
        void comboBox(nanobind::module_&);
        void confirmDialog(nanobind::module_&);
        void choiceDialog(nanobind::module_&);
        void inputDialog(nanobind::module_&);
        void itemButton(nanobind::module_&);
        void itemButtonList(nanobind::module_&);
        void diagWidget(nanobind::module_&);
        void dialogSystem(nanobind::module_&);
        void divider(nanobind::module_&);
        void documentModel(nanobind::module_&);
        void doubleEdit(nanobind::module_&);
        void doubleEditShuttle(nanobind::module_&);
        void doubleEditSlider(nanobind::module_&);
        void doubleModel(nanobind::module_&);
        void doubleSlider(nanobind::module_&);
        void drivesModel(nanobind::module_&);
        void event(nanobind::module_&);
        void fileBrowser(nanobind::module_&);
        void fileBrowserWidgets(nanobind::module_&);
        void fileEdit(nanobind::module_&);
        void floatEdit(nanobind::module_&);
        void floatEditShuttle(nanobind::module_&);
        void floatEditSlider(nanobind::module_&);
        void floatModel(nanobind::module_&);
        void floatSlider(nanobind::module_&);
        void flowLayout(nanobind::module_&);
        void formLayout(nanobind::module_&);
        void graphWidget(nanobind::module_&);
        void gridLayout(nanobind::module_&);
        void groupBox(nanobind::module_&);
        void iButton(nanobind::module_&);
        void iContainer(nanobind::module_&);
        void icon(nanobind::module_&);
        void iconSystem(nanobind::module_&);
        void iDialog(nanobind::module_&);
        void imageWidget(nanobind::module_&);
        void iMenuPopup(nanobind::module_&);
        void iMouseWidget(nanobind::module_&);
        void incButtons(nanobind::module_&);
        void intEdit(nanobind::module_&);
        void intEditShuttle(nanobind::module_&);
        void intEditSlider(nanobind::module_&);
        void intModel(nanobind::module_&);
        void intSlider(nanobind::module_&);
        void iPopup(nanobind::module_&);
        void iWidget(nanobind::module_&);
        void iWidgetPopup(nanobind::module_&);
        void iWindow(nanobind::module_&);
        void label(nanobind::module_&);
        void levelsSlider(nanobind::module_&);
        void lineEdit(nanobind::module_&);
        void lineEditModel(nanobind::module_&);
        void listItemsWidget(nanobind::module_&);
        void listWidget(nanobind::module_&);
        void mainWindow(nanobind::module_&);
        void mdiCanvas(nanobind::module_&);
        void mdiMiniMap(nanobind::module_&);
        void mdiWidget(nanobind::module_&);
        void menu(nanobind::module_&);
        void menuBar(nanobind::module_&);
        void messageDialog(nanobind::module_&);
        void overlayLayout(nanobind::module_&);
        void pieChart(nanobind::module_&);
        void progressDialog(nanobind::module_&);
        void pushButton(nanobind::module_&);
        void radioButton(nanobind::module_&);
        void recentFilesModel(nanobind::module_&);
        void rowLayout(nanobind::module_&);
        void screenshotTag(nanobind::module_&);
        void scrollArea(nanobind::module_&);
        void scrollBar(nanobind::module_&);
        void scrollWidget(nanobind::module_&);
        void searchBox(nanobind::module_&);
        void settings(nanobind::module_&);
        void shuttleWidget(nanobind::module_&);
        void spacer(nanobind::module_&);
        void splitter(nanobind::module_&);
        void splitter2D(nanobind::module_&);
        void stackLayout(nanobind::module_&);
        void style(nanobind::module_&);
        void svgWidget(nanobind::module_&);
        void sysLogModel(nanobind::module_&);
        void tabBar(nanobind::module_&);
        void tabWidget(nanobind::module_&);
        void textEdit(nanobind::module_&);
        void textEditModel(nanobind::module_&);
        void toolBar(nanobind::module_&);
        void toolButton(nanobind::module_&);
        void tooltip(nanobind::module_&);
        void widgetOptions(nanobind::module_&);
        void window(nanobind::module_&);

        void uiBind(nanobind::module_&);
    }
}
