// SPDX-License-Identifier: BSD-3-Clause
// Copyright Contributors to the feather-tk project.

#pragma once


#include <pybind11/pybind11.h>

namespace ftk
{
    namespace python
    {
        void action(pybind11::module_&);
        void actionGroup(pybind11::module_&);
        void app(pybind11::module_&);
        void bellows(pybind11::module_&);
        void buttonGroup(pybind11::module_&);
        void checkBox(pybind11::module_&);
        void clipboardSystem(pybind11::module_&);
        void colorPopup(pybind11::module_&);
        void colorSlider(pybind11::module_&);
        void colorDot(pybind11::module_&);
        void colorSwatch(pybind11::module_&);
        void colorWidget(pybind11::module_&);
        void comboBox(pybind11::module_&);
        void confirmDialog(pybind11::module_&);
        void choiceDialog(pybind11::module_&);
        void inputDialog(pybind11::module_&);
        void itemButton(pybind11::module_&);
        void itemButtonList(pybind11::module_&);
        void diagWidget(pybind11::module_&);
        void dialogSystem(pybind11::module_&);
        void divider(pybind11::module_&);
        void documentModel(pybind11::module_&);
        void doubleEdit(pybind11::module_&);
        void doubleEditShuttle(pybind11::module_&);
        void doubleEditSlider(pybind11::module_&);
        void doubleModel(pybind11::module_&);
        void doubleSlider(pybind11::module_&);
        void drivesModel(pybind11::module_&);
        void event(pybind11::module_&);
        void fileBrowser(pybind11::module_&);
        void fileBrowserWidgets(pybind11::module_&);
        void fileEdit(pybind11::module_&);
        void floatEdit(pybind11::module_&);
        void floatEditShuttle(pybind11::module_&);
        void floatEditSlider(pybind11::module_&);
        void floatModel(pybind11::module_&);
        void floatSlider(pybind11::module_&);
        void flowLayout(pybind11::module_&);
        void formLayout(pybind11::module_&);
        void graphWidget(pybind11::module_&);
        void gridLayout(pybind11::module_&);
        void groupBox(pybind11::module_&);
        void iButton(pybind11::module_&);
        void iContainer(pybind11::module_&);
        void icon(pybind11::module_&);
        void iconSystem(pybind11::module_&);
        void iDialog(pybind11::module_&);
        void imageWidget(pybind11::module_&);
        void iMenuPopup(pybind11::module_&);
        void iMouseWidget(pybind11::module_&);
        void incButtons(pybind11::module_&);
        void intEdit(pybind11::module_&);
        void intEditShuttle(pybind11::module_&);
        void intEditSlider(pybind11::module_&);
        void intModel(pybind11::module_&);
        void intSlider(pybind11::module_&);
        void iPopup(pybind11::module_&);
        void iWidget(pybind11::module_&);
        void iWidgetPopup(pybind11::module_&);
        void iWindow(pybind11::module_&);
        void label(pybind11::module_&);
        void levelsSlider(pybind11::module_&);
        void lineEdit(pybind11::module_&);
        void lineEditModel(pybind11::module_&);
        void listItemsWidget(pybind11::module_&);
        void listWidget(pybind11::module_&);
        void mainWindow(pybind11::module_&);
        void mdiCanvas(pybind11::module_&);
        void mdiMiniMap(pybind11::module_&);
        void mdiWidget(pybind11::module_&);
        void menu(pybind11::module_&);
        void menuBar(pybind11::module_&);
        void messageDialog(pybind11::module_&);
        void overlayLayout(pybind11::module_&);
        void pieChart(pybind11::module_&);
        void progressDialog(pybind11::module_&);
        void pushButton(pybind11::module_&);
        void radioButton(pybind11::module_&);
        void recentFilesModel(pybind11::module_&);
        void rowLayout(pybind11::module_&);
        void screenshotTag(pybind11::module_&);
        void scrollArea(pybind11::module_&);
        void scrollBar(pybind11::module_&);
        void scrollWidget(pybind11::module_&);
        void searchBox(pybind11::module_&);
        void settings(pybind11::module_&);
        void shuttleWidget(pybind11::module_&);
        void spacer(pybind11::module_&);
        void splitter(pybind11::module_&);
        void splitter2D(pybind11::module_&);
        void stackLayout(pybind11::module_&);
        void style(pybind11::module_&);
        void svgWidget(pybind11::module_&);
        void sysLogModel(pybind11::module_&);
        void tabBar(pybind11::module_&);
        void tabWidget(pybind11::module_&);
        void textEdit(pybind11::module_&);
        void textEditModel(pybind11::module_&);
        void toolBar(pybind11::module_&);
        void toolButton(pybind11::module_&);
        void tooltip(pybind11::module_&);
        void widgetOptions(pybind11::module_&);
        void window(pybind11::module_&);

        void uiBind(pybind11::module_&);
    }
}
